[project]
name = 'stxit-contract'
description = ''
authors = []
telemetry = true
cache_dir = '.\.cache'
requirements = []
[contracts.community-voting]
path = 'contracts/community-voting.clar'
clarity_version = 3
epoch = 3.0

[contracts.account-closure]
path = 'contracts/account-closure.clar'
[contracts.user-profile]
path = 'contracts/user-profile.clar'
clarity_version = 3
epoch = 3.0
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
